version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: agri_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: AssExpertsystem
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d AssExpertsystem"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agri_web_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=db
      - DATABASE_URL=postgresql+psycopg2://postgres:123@db:5432/AssExpertsystem
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
