"""Add expert system knowledge base

Revision ID: 166413aeb414
Revises: edf13db04ab2
Create Date: 2026-01-27 01:19:57.289907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166413aeb414'
down_revision = 'edf13db04ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rule_symptoms',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'symptom_id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('rules_disease_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'diseases', ['disease_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('symptoms')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('theme',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'auto'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('theme',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'auto'::character varying"))

    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symptoms', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rules_disease_id_fkey'), 'diseases', ['disease_id'], ['id'])

    op.drop_table('rule_symptoms')
    op.drop_table('symptoms')
    # ### end Alembic commands ###
