"""add_two_factor_verification_fields

Revision ID: 4e41abc172fe
Revises: t1u2v3w4x5y6
Create Date: 2026-06-29 13:44:53.003319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e41abc172fe'
down_revision = 't1u2v3w4x5y6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('two_factor_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('two_factor_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('two_factor_expiry')
        batch_op.drop_column('two_factor_code')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
