"""make farmer_id nullable

Revision ID: 5abe45f2e153
Revises: 88fcb8e24420
Create Date: 2026-08-27 17:40:56.369069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abe45f2e153'
down_revision = '88fcb8e24420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expert_diagnoses', schema=None) as batch_op:
        batch_op.alter_column('farmer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expert_diagnoses', schema=None) as batch_op:
        batch_op.alter_column('farmer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
