"""detect_missing

Revision ID: 62a8b52946e4
Revises: w4x5y6z7a8b9
Create Date: 2026-09-26 11:51:32.486033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a8b52946e4'
down_revision = 'w4x5y6z7a8b9'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    insp = sa.inspect(conn)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('detail',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    diag_cols = {c['name'] for c in insp.get_columns('expert_diagnoses')}
    if 'image_paths' not in diag_cols:
        with op.batch_alter_table('expert_diagnoses', schema=None) as batch_op:
            batch_op.add_column(sa.Column('image_paths', sa.JSON(), nullable=True))

    role_cols = {c['name'] for c in insp.get_columns('roles')}
    if 'route_type' not in role_cols:
        with op.batch_alter_table('roles', schema=None) as batch_op:
            batch_op.add_column(sa.Column('route_type', sa.String(length=50), server_default='farmer', nullable=False))

    user_cols = {c['name'] for c in insp.get_columns('users')}
    if 'ai_credits' not in user_cols:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('ai_credits', sa.Integer(), server_default='13000', nullable=False))

    try:
        conn.execute(sa.text("""
            ALTER TABLE expert_diagnoses DROP CONSTRAINT IF EXISTS expert_diagnoses_crop_id_fkey;
            ALTER TABLE expert_diagnoses ADD CONSTRAINT expert_diagnoses_crop_id_fkey FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE SET NULL;
            ALTER TABLE expert_diagnoses DROP CONSTRAINT IF EXISTS expert_diagnoses_disease_id_fkey;
            ALTER TABLE expert_diagnoses ADD CONSTRAINT expert_diagnoses_disease_id_fkey FOREIGN KEY (disease_id) REFERENCES diseases(id) ON DELETE SET NULL;
        """))
    except Exception:
        pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ai_credits')

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('route_type')

    with op.batch_alter_table('expert_diagnoses', schema=None) as batch_op:
        batch_op.drop_column('image_paths')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('detail',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
