"""Add attachments to AdminChatMessage

Revision ID: 88fcb8e24420
Revises: af419c464072
Create Date: 2026-08-13 14:55:33.309078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fcb8e24420'
down_revision = 'af419c464072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('attachment_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_chat_messages', schema=None) as batch_op:
        batch_op.drop_column('attachment_type')
        batch_op.drop_column('attachment_url')

    # ### end Alembic commands ###
