"""add last_credit_reset and increase credits

Revision ID: 9107ff5eedcd
Revises: e5baa5f83bf5
Create Date: 2026-08-27 20:47:22.130618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9107ff5eedcd'
down_revision = 'e5baa5f83bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_credit_reset', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_credit_reset')

    # ### end Alembic commands ###
