"""add ai_model and ai_api_key

Revision ID: a27721850b99
Revises: 81097056c8a0
Create Date: 2026-08-10 18:17:59.654058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a27721850b99'
down_revision = '81097056c8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_api_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ai_api_key')
        batch_op.drop_column('ai_model')

    # ### end Alembic commands ###
