"""add site settings and disease kh fields

Revision ID: fbda757b2e90
Revises: g1a2b3c4d5e6
Create Date: 2026-02-05 19:07:33.660229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbda757b2e90'
down_revision = 'g1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_kh', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('description_kh', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('treatment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('treatment_kh', sa.Text(), nullable=True))

    with op.batch_alter_table('mixed_agri_facts', schema=None) as batch_op:
        batch_op.drop_constraint('mixed_agri_facts_source_id_fact_text_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixed_agri_facts', schema=None) as batch_op:
        batch_op.create_unique_constraint('mixed_agri_facts_source_id_fact_text_key', ['source_id', 'fact_text'])

    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_column('treatment_kh')
        batch_op.drop_column('treatment')
        batch_op.drop_column('description_kh')
        batch_op.drop_column('name_kh')

    # ### end Alembic commands ###
